version: 2
sources:
  - name: STAGE
    description: This is source for publish
    database: DBT_SAMPLE
    tables:
      - name: CUSTOMER
      - name: ORDERS
      - name: LINEITEM
      - name: NATION
      - name: REGION
  - name: RAW
    description: This is source for stage
    database: DBT_SAMPLE
    tables:
      - name: CUSTOMER
      - name: ORDERS
      - name: LINEITEM
      - name: NATION
      - name: REGION
      - name: V_CUSTOMER 
      - name: V_LINEITEM
      - name: V_NATION
      - name: V_ORDERS
      - name: V_REGION